# Site settings
# in the templates available like {{ site.myvariable }}.
title: Люкс фурнитура для украшений
email: sacramento922@yandex.ru
brand: Люкс фурнитура
headline: Всё для создания украшений
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 479422

# Contacts
email: sacramento922@yandex.ru
phone: +375 25 919-69-72

# Tracking
# googleAnalitycsID: UA-83933844-1

